name: Deploy index.html to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy index.html to EC2
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ec2-user
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          echo "<!DOCTYPE html><html><body><h1>Hello, World!</h1></body></html>" > index.html
          sudo rm -rf /var/www/html/*
          sudo mv index.html /var/www/html/
          sudo systemctl restart httpd